apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-app
  title: scania-react-app
  description: Hello World React application using Scania Docker image
  annotations:
    github.com/project-slug: RamtilakChandrasekaran/backstage-app
spec:
  type: service
  lifecycle: production
  owner: Ramtilak-C
  dependencies:
  containers:
    - name: scania-app-container
      image: scania-app:latest
      ports:
        - port: 3000
