name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build and Push Docker Image
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        docker build -t scania-app:latest .
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN docker.io
        docker tag scania-app:latest ramtilakc/scania-app:latest
        docker push ramtilakc/scania-app:latest

    - name: Deploy Locally
      run: |
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN docker.io && docker-compose up -d
        echo "Application is accessible at http://localhost:4000"
